language: java
jdk: oraclejdk7

install: mvn package -DbuildNumber=$TRAVIS_BUILD_NUMBER -DciSystem=travis -Dcommit=${TRAVIS_COMMIT:0:7}
after_success:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "[[ \"$TRAVIS_BRANCH\" == \"master\" ]] && mvn deploy --settings target/travis/settings.xml"

notifications:
  email: false
  webhooks:
    - http://get.spout.org/hook
    - http://n.tkte.ch/h/1076/r5Wwubvw4r_SABhQgwfeL8WO

env:
  global:
    - secure: "Qd8wvxWJ4pK+JAZg6+iIH4uqN2DGVGc+tyLDJX3gJ/q4ES59cnzMOfgAXxIy1W/DIbjwqPp5BiO8JUjKDN8WIkq/zS4PokwebQaBIcHHx2ibNHHNcXl3B6eddC10ew5tDZZxYY628zqa/ABDJYOwCIVUEAQY8XRGdqtgVkR3CTw="
    - secure: "auZwWXS8kMGQ5tYQPNNTZgf8ztMKLgKz+DznP+Yp/uMAlSqZxMvcuz5AtxVzpsDC5cYazUXBPVguK4Pqby+kLHQYv0+dSTT+zYEK97n5VL/ZYpn6krrEsfPuilBacAnTBWOL5bhgNYTtKE2MgaO0ZnM3dNf4nZ+6idd2g4Iz8JY="
